### ISSUE TITLE
Some @2x images do not load in on iPhone/iPad running iOS8

### ISSUE THREAD

**Issue by liammoody** [imulus/retinajs#179]
We have a number of iPhones and iPads here, running a mix of iOS 7 and iOS 8... since updating those on iOS 8 and testing our site some of our images seem to not load in after retina.js runs. It just displays as a broken image (empty box with keyline and Alt Text showing).

Runs fine on desktop, and iPhones/iPads running iOS 7 or earlier.

Anyone else having trouble? Any ideas on how to fix?

**Comment by silverboxdev** [comment]
Same issue here - running them on localhost it always works - but when I load them up on the production server sometimes the images don't show. Nothing really different about the environments, not sure why it's not working all the time...

**Comment by powtac** [comment]
Same issue here. retina.js works fine in Firefox locally with retina fake settings: about:config -> `layout.css.devPixelsPerPx` = 2 but not on iPhone 6 and 6+.

**Comment by afs2015** [comment]
I just had this issue as well. Worked fine on google chrome emulator, didn't show up on the phone or tablet.

**Comment by joefaron** [comment]
Anyone have a solution?  I've had many reports now on iOS devices, loading broken images.. I think there's a way to tell in JS, if the image has properly loaded or not.. might have to look into that, but it's tough for me to reproduce the issue as it seems like devices on weak internet cause this to happen more often.

**Comment by powtac** [comment]
I added the data-at2x attribute to all img tags, this works fine now. 

<img src="/images/my_image.png" data-at2x="http://example.com/my_image@2x.png" />

**Comment by silverboxdev** [comment]
@powtac - did that turn out to officially work for you? This site has a ton of images so I wanted to see what you were experiencing before I recommend adding all that. Thanks so much man!

**Comment by powtac** [comment]
Worked for me! It is an official feature of retinajs. Check the docs.

**Comment by leanda** [comment]
I'm having the same problem. One or two thumbnails don't show on IOS. I've tried adding the `context.onload();` solution from @spadilha which fixes the problem but weirdly also starts to look for images with @2x@2x on the desktop and then shows 404 in the inspector when it can't find them.

I'm using WordPress, does anyone know how it might be possible to add the `data-at2x` attribute to img tags using the `echo get_the_post_thumbnail( $child_page->ID, 'medium');`?

**Comment by jcpeden** [comment]
I'm in the same boat - images are there and retina.js works using Chrome's emulator.

However, when I use Safari to debug with an iPad air, I can see the 2x images are not being loaded.

Neither the context.onload(); or data-at2x solutions worked for me.

**Comment by jcpeden** [comment]
Got it fixed the normal way of loading images. Might have been a caching issue?

**Comment by russd1977** [comment]
I'm also having this issue, some images don't load. Tried all the options above with no solution as yet.  Very strange as this issue has been going on for some time I see - perhaps there's no fix possible?

**Comment by joefaron** [comment]
Everything is fixable.. I've given up on it.. it's been better for me tho.

**Comment by jyoung913** [comment]
Used retina.js v1.3.0
Replacing `http.open('HEAD', this.at_2x_path);` with `http.open('GET', this.at_2x_path);` fixed my problem. This fix results in @2x images to be loaded twice so it is not very ideal, but you can add user agent detection and apply it only to iOS devices, and the second load actually comes from cache so it is not that bad.

I thought about this fix because @powtac mentioned that data-at2x attribute fixes the problem, I reviewed the code and found out the difference between setting data-at2x or not is here: 
```javascript
else {
            http = new XMLHttpRequest();
            http.open('HEAD', this.at_2x_path);
            http.onreadystatechange = function() {
                if (http.readyState !== 4) {
                    return callback(false);
                }

                if (http.status >= 200 && http.status <= 399) {
                    if (config.check_mime_type) {
                        var type = http.getResponseHeader('Content-Type');
                        if (type === null || !type.match(/^image/i)) {
                            return callback(false);
                        }
                    }

                    RetinaImagePath.confirmed_paths.push(that.at_2x_path);
                    return callback(true);
                } else {
                    return callback(false);
                }
            };
            http.send();
        }
```
I also observed that original image show briefly before being replaced by blank images, so I suspect that HEAD method causes iOS Safari (by the way, my Chrome for iOS works fine with original retina.js) to wrongly cache data returned from the HEAD request.

If you have all your images with @2x version, I also found that replacing `this.perform_check = true;` with `this.perform_check=false;` solves the problem, this approach is identical to the data-at2x attribute fix but you don't need to manually add attribute to all your images. The downside of this is that any image without a @2x version will be broken on a high density screen, so you may want to add data-no-retina attribute to images with no @2x version.
