### ISSUE TITLE
Only kick in when ratio is at 2 or above?

### ISSUE THREAD

**Issue by goatwriter** [imulus/retinajs#190]
Hi, great tool thanks.
Is there a way to edit the script so that it will only kick in at a ratio of 2 or above, and not before? 

At the moment any zoom triggers the loading of the @2x images, e.g., 125% zoom - quite a common setting people have just to make text a little bigger.

**Comment by jgnewman** [comment]
Great idea! Sorry for the late response, we'll get right on that.

**Comment by Lori1072** [comment]
Hey, Guys I truly appreciate your help with this coding. Can  ask why is there continuous issues with retinas? Is this the theme ? Thank You Kindly...Lori

**Comment by jgnewman** [comment]
Hi Lori, I'm not sure I completely understand the question. If you're asking why retina.js seems to have a lot of issues filed, it's for a couple of reasons. All software has bugs, for one, and we have to continually make it better and better. In our case, many of the issues here are actually feature requests instead of bugs. And some of the bugs are looking like they might actually be with the LESS compiler instead of our JavaScript. All in all, I'd say retina.js does pretty well for what it is :)




On the other hand, if you're asking why it's been a while since we've taken a lot of action against these issues, it's because we're an agency and sometimes our workload stretches us all pretty thin. Hopefully we're entering a stretch now where we can start knocking some of these issues out.




Let me know if that doesn't answer your question. Thanks for your interest!



—
